CREATE DATABASE CUSTOMER;
USE CUSTOMER;
CREATE TABLE customer_purchases (
    CustomerID VARCHAR(50),
    Age INT,
    Gender VARCHAR(10),
    ItemPurchased VARCHAR(100),
    Category VARCHAR(50),
    PurchaseAmountUSD DECIMAL(10,2),
    Location VARCHAR(100),
    Size VARCHAR(20),
    Color VARCHAR(30),
    Season VARCHAR(20),
    ReviewRating DECIMAL(3,1),
    SubscriptionStatus VARCHAR(20),
    ShippingType VARCHAR(50),
    DiscountApplied VARCHAR(10),
    PromoCodeUsed VARCHAR(10),
    PreviousPurchases INT,
    PaymentMethod VARCHAR(50),
    FrequencyOfPurchases VARCHAR(50)
);
SELECT * FROM customer_purchases LIMIT 20;
SELECT COUNT(*) FROM customer_purchases;

-- Q1. What is the total revenue generated by male vs. female customers?
Select gender,sum(PurchaseAmountUSD) as revenue from customer_purchases group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
Select customerID,PurchaseAmountUSD from customer_purchases where DiscountApplied = "Yes" and PurchaseAmountUSD >= (Select AVG(PurchaseAmountUSD) from customer_purchases);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT  ItemPurchased ,ROUND(AVG(ReviewRating),2) AS AVG_REVIEW FROM customer_purchases GROUP BY ItemPurchased ORDER BY AVG(ReviewRating) DESC LIMIT 5; 

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
Select ShippingType,ROUND(AVG(PurchaseAmountUSD),2) as Avg_purchase_amount from customer_purchases WHERE ShippingType IN ("Express","Standard") group by ShippingType;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
Select SubscriptionStatus,count(CustomerID) AS Total_customer,ROUND(AVG(PurchaseAmountUSD),2) as Avg_spend,sum(PurchaseAmountUSD) AS Total_revenue 
from customer_purchases WHERE SubscriptionStatus IN ("Yes","No") group by SubscriptionStatus;
-- or
SELECT SubscriptionStatus,
       COUNT(CustomerID) AS total_customers,
       ROUND(AVG(PurchaseAmountUSD),2) AS avg_spend,
       ROUND(SUM(PurchaseAmountUSD),2) AS total_revenue
FROM customer_purchases
GROUP BY SubscriptionStatus
ORDER BY total_revenue,avg_spend DESC;

-- Which 5 products have the highest percentage of purchases with discounts applied?
select  ItemPurchased ,count(*) as total_purchase ,
SUM(CASE WHEN DiscountApplied = "Yes" THEN 1 ELSE 0 END) AS DISCOUNT_PURCHASE,
(SUM(CASE WHEN DiscountApplied = "Yes" THEN 1 ELSE 0 END)/count(*))*100.0 AS DISCOUNT_PERCENTAGE
from  customer_purchases GROUP BY ItemPurchased ORDER BY DISCOUNT_PERCENTAGE DESC LIMIT 5;
-- OR
SELECT ItemPurchased ,
       ROUND(100.0 * SUM(CASE WHEN DiscountApplied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
from  customer_purchases GROUP BY ItemPurchased ORDER BY discount_rate DESC LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
SELECT 
    CASE 
        WHEN PreviousPurchases = 1 THEN 'New'
        WHEN PreviousPurchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS Customer_Segment,
    COUNT(*) AS Count_of_Customers
FROM customer_purchases
GROUP BY Customer_Segment;

-- OR
WITH customer_type AS (
    SELECT 
        CustomerID, 
        PreviousPurchases,
        CASE 
            WHEN PreviousPurchases = 1 THEN 'New'
            WHEN PreviousPurchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS Customer_Segment
    FROM customer_purchases
)

SELECT 
    Customer_Segment,
    COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY Customer_Segment;

-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           ItemPurchased,
           COUNT(CustomerID) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(CustomerID) DESC) AS item_rank
    FROM customer_purchases
    GROUP BY Category, ItemPurchased
)
SELECT item_rank,Category, ItemPurchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT SubscriptionStatus,
       COUNT(CustomerID) AS repeat_buyers
FROM customer_purchases
WHERE PreviousPurchases > 5
GROUP BY SubscriptionStatus;

-- Q10. What is the revenue contribution of each age group? 
SELECT 
    CASE
        WHEN Age BETWEEN 18 AND 30 THEN 'Young Adult'
        WHEN Age BETWEEN 31 AND 45 THEN 'Adult'
        WHEN Age BETWEEN 46 AND 60 THEN 'Middle-aged'
        ELSE 'Senior citizen'
    END AS Age_group,
    ROUND(SUM(PurchaseAmountUSD), 0) AS total_revenue
FROM
    customer_purchases
GROUP BY Age_group
ORDER BY total_revenue DESC;




-- CUSTOMER ANALYSIS

-- 1. CUSTOMER SEGMENTATION
-- Classify customers as New, Returning, Loyal based on Previous Purchases.
WITH customer_type AS (
    SELECT 
        CustomerID, 
        PreviousPurchases,
        CASE 
            WHEN PreviousPurchases = 1 THEN 'New'
            WHEN PreviousPurchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS Customer_Segment
    FROM customer_purchases
)

SELECT 
    Customer_Segment,
    COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY Customer_Segment;

-- 2. High Value Customers (VIP)
-- Identify customers who spend the highest total amount.
SELECT CustomerID,SUM(PurchaseAmountUSD) AS Highest_purchase_amount from customer_purchases group by CustomerID order by  Highest_purchase_amount desc limit 10;

-- 3. Customer Behavior by Age Group
-- Which age groups spend the most?
SELECT 
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN 'Gen Z Shoppers'
        WHEN Age BETWEEN 26 AND 35 THEN 'Millennial Shoppers'
        WHEN Age BETWEEN 36 AND 45 THEN 'Established Families'
        WHEN Age BETWEEN 46 AND 60 THEN 'Experienced Consumers'
        ELSE 'Golden Age Consumers'
    END AS Age_group,
    ROUND(SUM(PurchaseAmountUSD), 0) AS total_revenue
FROM
    customer_purchases
GROUP BY Age_group
ORDER BY total_revenue DESC;

-- PRODUCT & SALES ANALYSIS
-- 1. Best Performing Categories
-- Which categories generate the most revenue?
SELECT Category,SUM(PurchaseAmountUSD) AS total_revenue,
RANK() OVER (ORDER BY SUM(PurchaseAmountUSD) DESC) AS Revenue_Rank
FROM customer_purchases
GROUP BY Category order by total_revenue desc;

-- 2. Seasonal Trends
-- Which season has the highest sales?
select Season,SUM(PurchaseAmountUSD) AS highest_sales from customer_purchases
GROUP BY Season Order by highest_sales desc;

-- 3. Discount Impact
-- Does giving discounts actually increase sales volume?

SELECT 
    CASE 
        WHEN (DiscountApplied) = 'Yes' THEN 'With Discount'
        ELSE 'Without Discount'
    END AS Discount_Status,
    ROUND(AVG(PurchaseAmountUSD),2) AS Avg_Purchase_Amount
FROM 
    customer_purchases
GROUP BY 
    CASE 
        WHEN (DiscountApplied) = 'Yes' THEN 'With Discount'
        ELSE 'Without Discount'
    END;
    
-- 4. Product Quality Check
-- Which products get the highest and lowest review ratings?
-- Top 5 highest-rated items
SELECT 
    (ItemPurchased),
    AVG(ReviewRating) AS Avg_Rating
FROM 
    customer_purchases
GROUP BY 
    (ItemPurchased)
ORDER BY 
    Avg_Rating DESC
LIMIT 5;
-- Bottom 5 lowest-rated items
SELECT 
    (ItemPurchased),
    AVG(ReviewRating) AS Avg_Rating
FROM 
    customer_purchases
GROUP BY 
    (ItemPurchased)
ORDER BY 
    Avg_Rating ASC
LIMIT 5;

-- MARKETING & PROMOTION ANALYSIS 
-- 1. Discount Dependency
-- Which customers ONLY purchase when a discount is applied?

SELECT CustomerID
FROM customer_purchases
GROUP BY CustomerID
HAVING SUM(CASE WHEN (DiscountApplied) = 'No' THEN 1 ELSE 0 END) = 0;


